### ISSUE TITLE
Line sources are disabled in FullMonte - need to reenable and test

### ISSUE THREAD

**Issue by vaughnbetz** [fullmonte-for-PDT/fullmonte-source-code#1]
FullMonte line source is disabled in /Kernels/Software/Emitters/TetraMeshEmitterFactory.cpp. (according to Siyun on August 4).
Not sure if the code is broken and hence disabled, or if there is some other reason why it's disabled.

**Comment by AbedYassine** [comment]
After investigating this, I found that TetraEmitterFactory::doVisit(Line* l) is commented out in the latest version of FullMonte, as it depends on a class called "RayWalk" which is also commented out. I tried uncommenting and compiling, but got errors related to class "TetraMesh" missing some member functions. It turns out that in the latest version, class "TetraMesh" inherits from a new class called "Geometry", while in the previous version it used to inherit from class "TetraMeshBase" that had all those missing members and now is deprecated.

**Comment by vaughnbetz** [comment]
OK, I think we have 3 options then.
1. Use the old version of FullMonte.  Not a long term solution, but doable to unblock Abed.
2. Abed gets some guidance from Jeff on how to update the latest FullMonte to move / update / recode the missing member functions, and then he makes those changes.  You can use your regression test of a line source to validate that your code changes work Abed, and then could commit the code and the test.
3. Jeff finishes the refactoring / updates that would reenable line sources.

If it's doable I lean toward 2, as Jeff already has multiple open items, and it would get Abed familiar with coding in FullMonte, which is important so we don't have a single developer (Jeff) to maintain and enhance FullMonte.  Any thoughts Abed and Jeff?

**Comment by vaughnbetz** [comment]
Talked to Abed and Jeff; we will go with option 2.

**Comment by jeffreycassidy** [comment]
Abed has completed & committed.
One remaining limitation (not relevant to line sources): all pieces of segment must be inside mesh. 
Thanks Abed!
