### ISSUE TITLE
Test script is not running FullMonte scripts to generate output for comparison

### ISSUE THREAD

**Issue by AbedYassine** [fullmonte-for-PDT/fullmonte-source-code#19]
The buildbot test script is not running the different FullMonte scripts that generate new output for comparison tests

**Comment by vaughnbetz** [comment]
Yasmin is this fixed?
To confirm it is fixed, please break fullMonte (e.g. multiply all output by 2) and confirm the automatic tests flag a failure.

**Comment by yasmin-afsharnejad** [comment]
I modified this function in FullMonteSW/OutputTypes/OutputDataCollection.cpp. which is collecting the results of FullMonteSW kernel. 

I added 2 to the results (*it). 

OutputData* OutputDataCollection::getByIndex(unsigned i)
{
        list<OutputData*>::iterator it; 
        for(it = m_contents.begin(); it != m_contents.end() && i; --i, ++it)
                {}
  //return it == m_contents.end() ? nullptr : (*it );
        return it == m_contents.end() ? nullptr : (*it +2);
}


Test_FullMonte_MMC_Comparison FAILED.

Let me know, If there are more cases needed to be tested. Otherwise, we can close the issue. 
 @vaughnbetz @jeffreycassidy

**Comment by vaughnbetz** [comment]
Thanks Yasmin.  That is enough of a test in my opinion. 
As Jeff requested please note the commit id that fixed this in the issue tracker and then you can close this.

**Comment by jeffreycassidy** [comment]
@vaughnbetz did you realize that @yasmin-afsharnejad 's code snippet above adds 2 to a pointer, not to data?
Either it causes a crash, or that pointer is disregarded and the test doesn't test anything. Not sure if it's the sort of test you're looking for. Test failure will be due to invalid pointer rather than valid detection of a result difference.

**Comment by vaughnbetz** [comment]
Whoops, didn't look closely enough.  I'd also like a test where the final output is simply wrong (not a crash) -- i.e. all the numbers are incorrect.  Please try that case as well Yasmin.

**Comment by yasmin-afsharnejad** [comment]
Two tests have been done to ensure the automatic build works:
1)
Software/Logger/VolumeAbsorptionScorer.cpp
### `void VolumeAbsorptionScorer::postResults(OutputDataCollection* C) const
{
    // convert to float
    std::vector<float> vf(m_acc.size());

    for(unsigned i=0;i<m_acc.size();++i)
   	 vf[i] = m_acc[i];

    // create vector
    SpatialMap<float> *vmap = new SpatialMap<float>(std::move(vf),AbstractSpatialMap::Volume,AbstractSpatialMap::Scalar);

    vmap->quantity(&Units::energy);
    vmap->units(&Units::packet);

    vmap->name("VolumeEnergy");

    C->add(vmap);
}
`
I modified 	 _vf[i] = m_acc[i];_ to 	 _vf[i] = 2*m_acc[i];_ This function computes volume absorption. Applying this change,  doubled the values generated as results of running FullMonteSW in output files. All Siyun' tests failed by applying this change. 
2)
OutputTypes/MCConservationCounts.cpp
### `MCConservationCounts& MCConservationCounts::operator+=(const MCConservationCounts& cc)
{
    w_launch     += cc.w_launch;
    w_absorb     += cc.w_absorb;
    w_die   	 += cc.w_die;
    w_exit  	 += cc.w_exit;
    w_roulette     += cc.w_roulette;
    w_abnormal     += cc.w_abnormal;
    w_nohit   	 += cc.w_nohit;
    w_time		 += cc.w_time;
    return *this;
}
`
I modified _w_absorb     += cc.w_absorb;_  to  _w_absorb     += 2*cc.w_absorb;_
The _MCConservationCounts_ is used in Test_Mouse. So by applying the above change, this test failed.

**Comment by jeffreycassidy** [comment]
Can you provide the name of the failing test(s) and the commit that fixed the problem (ie. ensured that the new data was being run and checked)?
Thanks

Jeff

**Comment by yasmin-afsharnejad** [comment]
Commit 3d825efd0  includes the lines added to the Run_ctest.sh script to run FullMonteSW in order to generate vtk files which will be compared to Expected Results of tests. 
I added a new commit to refactor those lines for more readability. Commit ID:  a6b38017d .

Point number#1-> 
ctest -R Test_FullMonte_MMC_Comparison 
ctest -R Test_FullMonte_Self
ctest -R Test_FullMonte_Approx
ctest -R Test_FullMonte_Composite
 
Point number#2-> Test_Mouse failed.
